version: '3.12.6'

services:
  dash:
    command: python main.py
    image: pratibha2025/ait-ml-a3-dash:latest1
    #platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80

volumes:
  vscode-server: